// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqSt-3aWyuXil-qn8V5Kn3qE4NaKf6KyI',
    appId: '1:239787574751:web:48a1ed9cb212e0b7d8706a',
    messagingSenderId: '239787574751',
    projectId: 'mangoai-9c366',
    authDomain: 'mangoai-9c366.firebaseapp.com',
    storageBucket: 'mangoai-9c366.appspot.com',
    measurementId: 'G-XM451ZVRPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Bf8zZxulyN45zjCvIhVRhBmg5yW0sFg',
    appId: '1:239787574751:android:bb9627fef87ea386d8706a',
    messagingSenderId: '239787574751',
    projectId: 'mangoai-9c366',
    storageBucket: 'mangoai-9c366.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjl7gmFdPnCY-hxXQ4kqy38IPAp_TzvRE',
    appId: '1:239787574751:ios:6b3eee61b95f7dc2d8706a',
    messagingSenderId: '239787574751',
    projectId: 'mangoai-9c366',
    storageBucket: 'mangoai-9c366.appspot.com',
    iosClientId: '239787574751-qo5ph6mcc1j770gglp6bommrekeob706.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjl7gmFdPnCY-hxXQ4kqy38IPAp_TzvRE',
    appId: '1:239787574751:ios:cbe2da01efd69d05d8706a',
    messagingSenderId: '239787574751',
    projectId: 'mangoai-9c366',
    storageBucket: 'mangoai-9c366.appspot.com',
    iosClientId: '239787574751-b9ugcsnqklj8qclaqohcepl811lbgp78.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangoAi.RunnerTests',
  );
}
